version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "80:80"
    depends_on:
      - mongodb
    working_dir: /code/app
    volumes:
      - ./app:/code/app

  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    command:
      mongod --quiet --logpath /dev/null
    restart: unless-stopped
